### ISSUE TITLE
Lag while zooming the pdf

### ISSUE THREAD

**Issue by Rajkiran93** [ClassicalDude/pdfView-Freedraw#3]
Hey Ron, I followed you from stack and medium source...Thanks for the project although the performance has significantly improved but still I see a lot of lag while zooming the pdf, are there any more tricks or techniques to overcome this memory issue. I critically need to over come this particular issue because of my company requirements. This issue becomes worse when I use ipads instead of pro's......Thanks.
Im truly sorry I'm bugging you in all the corners....I would be very thank full if you could help me solve this issue.

**Comment by ClassicalDude** [comment]
Do you witness lag when you are using the demo app? Can you tell me exactly the circumstances?

**Comment by Rajkiran93** [comment]
In demo app which I used, there is no lag while writing but after filling the entire page and when I start scrolling or zooming the page there is noticeable amount of lag. In some cases i saw the memory peak to 1.5 GB.
Thanks...

**Comment by ClassicalDude** [comment]
That doesn't sound like the fault of my free draw framework, but rather the fault of PDFKit itself. To test this, please replace the default PDF file of the demo project with a heavily annotated file that you prepare in advance, and see if there is a lag from the moment you launch the app, even before adding any annotations to the existing ones. Remember - we are talking about a lot of free draw annotations, not text annotations. I believe that the process of converting the PDF information to the app's view stack weighs very heavily on the memory and the processor, and that's the source of the problem. As long as things are kept in the iOS view stack and layers, performance should be smooth.

If this is indeed the problem, I am not sure that the solution is within the scope of this project. However, it will most likely look like this:
- You would retain all of the CAShapeLayer annotations, and not use touchesEnded to destroy them or record anything to the PDF file
- You would only convert everything to the PDF coordinates and record the annotations to the PDF when you finish working with the file.

Please do the test I describe in the first paragraph above, and let me know if the lag is there from the very beginning.

**Comment by Rajkiran93** [comment]
Thanks for the quick reply, I agree with you its the issue with PDFKIT itself, here's what I have tried:
1. As you said I added all the ink annotation path to pdf only while saving it to disk. This works better but this conflicts other features in my app
2. I added outer scrollview to PDFView and disabled PDFKIT default zoom thinking this would take the performance load but still not that performant.

**One last question:** Does freehand drawing on UIView solve the memory and lag issues?

Lastly, If you could make detailed tutorial on how you found this issue "After a lot of testing, I realised that deleted annotations are not really purged from the PDFPage, and that this has great performance impact." in medium I think people would truly love it. 

**Nevertheless, you have created really wonderful framework it has reduced 50% of my effort, I'm still trying to perfect it. Thank you very much.**

**Comment by ClassicalDude** [comment]
Thank you for the compliment. I am very glad the framework helped you.

I do believe that working on a UIView directly has minimal performance impact. That's what it was designed to do. I went with the current approach because of two reasons:
1. For my purposes (music annotation) I do not expect the amount of annotations to be such that performance will be significantly impacted
2. In all of the apps I know that incorporate annotation, and go the UIView way, there seem to be issues with annotations getting misplaced or lost. With the current approach I know that the information is safe and sound within the PDF container.

Therefore, if there is a way to overcome the conflicts in your app, I would try to go with writing the annotations to the PDF just before saving (or when the app goes to the background).

Regarding what I discovered about annotations not being deleted - it is quite simple. Try this:

```swift
let annotations = self.pdfView.currentPage?.annotations
if annotations!.count == 3 {
    for annotation in annotations! {
        self.pdfView.currentPage?.removeAnnotation(annotation)
    }
    print ("count: \(annotations?.count)")
}
```
With this code, as soon as you have 3 annotations in the page, it attempts to delete them all, and then print how many annotations you have in the page. The result remains 3, and the performance remains the same. Do you think this warrants an essay in Medium?

**Comment by Rajkiran93** [comment]
I think I would go with this method for now **"I would try to go with writing the annotations to the PDF just before saving (or when the app goes to the background)."** until I find a different approach or Apple would fix the memory issues(in which case takes millennia to fix it). And yeah no need for medium post for this small snippet:-). Thank you Ron... for your time 👍
