### ISSUE TITLE
SwiftUI API

### ISSUE THREAD

**Issue by mikekllr** [ClassicalDude/pdfView-Freedraw#5]
Thank you for the project. Is there a way to implement this in SwiftUI?

**Comment by ClassicalDude** [comment]
It's open source. Feel free to fork the project and work on an implementation. At the moment I don't have plans to pursue this.

**Comment by mikekllr** [comment]
Here is a Way to get this up and running in SwiftUI.

```
import Foundation
import SwiftUI
import UIKit
import PDFKit


struct PDFKitEditorView: View {
    var url: URL
    var body: some View {
        PDFKitEditorRepresentedView(url)
    }
}

struct PDFKitEditorRepresentedView: UIViewControllerRepresentable {
    
    let url: URL
    
    init(_ url: URL) {
        self.url = url
    }
    
    func makeUIViewController(context: Context) -> UIViewController {
        
        let storyboard = UIStoryboard(name: "MainPDFView", bundle: Bundle.main)
        let controller = storyboard.instantiateViewController(withIdentifier: "PDFViewControllerID")
        
        return controller
    }
    
    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {
        
    }
    
   
}
```

**Comment by ClassicalDude** [comment]
Thank you! I'll post a link to your code on the README.

**Comment by federicaCapobianco** [comment]
Hi, I'm getting this error, I implemented the precompiled  framework and used your solution to embed it in a swiftUIView, don't know what I am missing

Thread 1: "Could not find a storyboard named 'MainPDFView' in bundle NSBundle

**Comment by ClassicalDude** [comment]
I am afraid I am still stuck in the world of storyboards rather than swiftUI (I wanted my apps to keep running on iOS12 devices). mikekllr's solution is to combine the two. PDFFreedrawGestureRecognizer is written for UIKit with storyboards, so you have to create a storyboard within your app (in his code, he named it "MainPDFView"). Add a Swift class file for a PDFViewController (a subclass of UIViewController), and make sure the UIViewController on your storyboard is pointing to the class you created. Then give that storyboard PDFViewController the storyboardID "PDFViewControllerID". Any interaction with the PDF file and PDFFreedrawGestureRecognizer will happen within the PDFViewController class. In your swiftUI app you'll only have to bring up that view controller.

Please let me know if this solves your problem; if there are additional steps on the way to solution, please detail them as well so I can update the documentation.

Edit: Got it to work on a sample app. Here is my contentView. Please continue reading instructions below the code.
```
import Foundation
import SwiftUI
import UIKit
import PDFKit

struct ContentView: View {
    @State private var presented = false
    var body: some View {

       // some other code that activates `presented` state
        let pdfURL = Bundle.main.url(forResource:"blank", withExtension: "pdf")!
        PDFKitEditorView(url: pdfURL)
          .sheet(isPresented: $presented) {
              PDFKitEditorRepresentedView(pdfURL)
          }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}

struct PDFKitEditorView: View {
    var url: URL
    var body: some View {
        PDFKitEditorRepresentedView(url)
    }
}

struct PDFKitEditorRepresentedView: UIViewControllerRepresentable {
    
    let url: URL
    
    init(_ url: URL) {
        self.url = url
    }
    
    func makeUIViewController(context: Context) -> UIViewController {
        
        let storyboard = UIStoryboard(name: "MainPDFView", bundle: Bundle.main)
        let controller = storyboard.instantiateViewController(withIdentifier: "PDFViewControllerID")
        
        return controller
    }
    
    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {
        
    }
    
}
```

I added to my bundle a file with a blank PDF page, named blank.pdf. The PDFViewController class was based on the sample one included in the package.
